openapi: 3.0.2

info:
  title: Inventory API
  description: Inventory API with Atp, Reservations
  version: '1.0.0' #api version


tags:
  - name: inventory

servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server

paths:

  /v1/atp:
    get:
      summary: Get the available to promise inventory 
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AtpResponse'


components:
  schemas:
    # AtpRequest:
    #   properties: 
    #     atp: 
    #       type: array
    #       items:
    #         -
    #         type: object
    #           properties: 
    #             skuId: 
    #                 type: string
    #             site: 
    #               type: string
    #             qty: 
    #               type: integer
    #             promiseDate: 
    #               type: string

    AtpResponse:
        type: array
        items: 
          type: object
          properties:
            skuId:
              type: string
            site:
              type: string
            qty:
              type: number