openapi: 3.0.2

info:
  title: Inventory API
  description: Inventory API with Atp, Reservations
  version: '1.0.0' #api version


tags:
  - name: inventory

servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server

paths:

  /v1/atp:
    post:
      summary: Post available to promise inventory 
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtpRequest'
      responses:
        '200':
          description: Successful
    get:
      summary: Get available to promise inventory 
      parameters:
        - in: query
          name: skuId
          required: true
          schema:
            type: string
          description: The name identified as inventory Sku
        - in: query
          name: site
          schema:
            type: string
          description: The location for inventory e.g. DC or Store

  /v1/reserve:
    post:
      summary: Post reservations 
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveRequest'
      responses:
        '200':
          description: Successful
    get:
      summary: Get reservations
      parameters:
        - in: query
          name: skuId
          required: true
          schema:
            type: string
          description: The name identified as inventory Sku
        - in: query
          name: site
          schema:
            type: string
          description: The location for inventory e.g. DC or Store
       
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ReserveResponse'


components:
  schemas:
    AtpRequest:
      type: object
      properties:
        atp: 
          type: array
          items:
            type: object
            properties:
              skuId:
                type: string
              site:
                type: string
              qty:
                type: number
              promiseDate:
                type: string
                format: date-time

    AtpResponse:
        type: array
        items: 
          type: object
          properties:
            skuId:
              type: string
            site:
              type: string
            qty:
              type: number
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    ReserveRequest:
      type: object
      properties:
        reservations: 
          type: array
          items:
            type: object
            properties:
              skuId:
                type: string
              site:
                type: string
              qty:
                type: number
              expiresIn:
                type: number
                
    ReserveResponse:
        type: array
        items: 
          type: object
          properties:
            skuId:
              type: string
            site:
              type: string
            reservationId:
              type: string
            qty:
              type: number
            expiresAt:
              type: string
              format: date-time
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time