openapi: 3.0.2

info:
  title: Inventory API
  description: Inventory API with Atp, Reservations
  version: '1.0.0' #api version


tags:
  - name: inventory

paths:

  /v1/atp:
    post:
      summary: Posts the available to promise inventory 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AtpRequest"
      responses:
        "200":
          description: "Successfully authorized payment request with Paymetric."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AtpResponse"

        # "400":
        #   description: "Bad Request Exception"
        #   content:
        #     application/json:
        #       schema:
        #         $ref: "#/components/schemas/ResponseError"
        # "500":
        #   description: "Internal Server Error"
        #   content:
        #     application/json:
        #       schema:
        #         $ref: "#/components/schemas/ResponseError"


components:
  schemas:
    AtpRequest:
      properties: 
        atp: 
          type: array
          items:
            type: object
              properties: 
                skuId: 
                    type: string
                site: 
                  type: string
                qty: 
                  type: integer
                promiseDate: 
                  type: string

    AtpResponse:
      properties:
      
    
